/* eslint-disable max-len */
const StudyPrograms = [
  "Aerospace Studies Minor",
  "African American and Diaspora Studies Minor",
  "African Studies Minor",
  "African, African American, and Diaspora Studies Major, B.A.",
  "American Indian and Indigenous Studies Minor",
  "American Studies Major, B.A.",
  "American Studies Major, B.A.–American Indian and Indigenous Studies Concentration",
  "American Studies Major, B.A.–Folklore Concentration",
  "American Studies Major, B.A.–Global American Studies Concentration",
  "American Studies Major, B.A.–Southern Studies Concentration",
  "American Studies Minor",
  "Anthropology (General) Minor",
  "Anthropology Major, B.A.",
  "Applied Sciences and Engineering Minor",
  "Arabic Minor",
  "Archaeology Major, B.A.",
  "Archaeology Minor",
  "Art History Major, B.A.",
  "Art History Minor",
  "Asian Studies Major, B.A.–Arab Cultures Concentration",
  "Asian Studies Major, B.A.–Chinese Concentration",
  "Asian Studies Major, B.A.–Interdisciplinary Concentration",
  "Asian Studies Major, B.A.–Japanese Concentration",
  "Asian Studies Major, B.A.–Korean Studies Concentration",
  "Asian Studies Major, B.A.–South Asian Studies Concentration",
  "Asian Studies Minor",
  "Astronomy Minor",
  "Biology Major, B.A.",
  "Biology Major, B.S.",
  "Biology Major, B.S.–Quantitative Biology Track",
  "Biology Minor",
  "Biomedical and Health Sciences Engineering Major, B.S.",
  "Biostatistics Major, B.S.P.H.",
  "Business Administration Major, B.S.B.A.",
  "Business Administration Minor",
  "Business Journalism Major, B.A.",
  "Certificate Programs in Media and Journalism",
  "Chemistry Major, B.A.",
  "Chemistry Major, B.S.",
  "Chemistry Major, B.S.–Biochemistry Track",
  "Chemistry Major, B.S.–Polymer Track",
  "Chemistry Minor",
  "Chinese Minor",
  "Classical Humanities Minor",
  "Classics Major, B.A.–Classical Archaeology",
  "Classics Major, B.A.–Classical Civilization",
  "Classics Major, B.A.–Greek, Latin, and Combined Greek and Latin",
  "Clinical Laboratory Science Major, B.S.",
  "Coaching Education Minor",
  "Cognitive Science Minor",
  "Communication Studies Major, B.A.",
  "Comparative Literature Minor",
  "Composition, Rhetoric, and Digital Literacy Minor",
  "Computer Science Major, B.A.",
  "Computer Science Major, B.S.",
  "Computer Science Minor",
  "Conflict Management Minor",
  "Contemporary European Studies Major, B.A.",
  "Creative Writing Minor",
  "Dental Hygiene Major, B.S.",
  "Doctor of Dental Surgery, D.D.S.",
  "Dramatic Art Major, B.A.",
  "Dramatic Art Minor",
  "Economics Major, B.A.",
  "Economics Major, B.S.",
  "Education Minor",
  "English and Comparative Literature Major, B.A.",
  "English Minor",
  "Entrepreneurship Minor",
  "Environmental Health Sciences Major, B.S.P.H.",
  "Environmental Justice Minor",
  "Environmental Science and Studies Minor",
  "Environmental Science, B.S.",
  "Environmental Studies Major, B.A.",
  "Exercise and Sport Science Major, B.A.–Fitness Professional",
  "Exercise and Sport Science Major, B.A.–General",
  "Exercise and Sport Science Major, B.A.–Sport Administration",
  "Exercise and Sport Science Minor",
  "Folklore Minor",
  "Food Studies Minor",
  "French Minor",
  "Geographic Information Sciences Minor",
  "Geography Major, B.A.",
  "Geography Minor",
  "Geological Sciences Major, B.A.–Earth Science Concentration",
  "Geological Sciences Major, B.S.–Earth Science Concentration",
  "Geological Sciences Major, B.S.–Environmental Geoscience Concentration",
  "Geological Sciences Minor",
  "German Minor",
  "Germanic and Slavic Languages and Literatures Major, B.A.– Central European Studies Concentration",
  "Germanic and Slavic Languages and Literatures Major, B.A.–German Literature and Culture Concentration",
  "Germanic and Slavic Languages and Literatures Major, B.A.–German Media, Arts, and Culture Concentration",
  "Germanic and Slavic Languages and Literatures Major, B.A.–Russian Language and Culture Concentration",
  "Germanic and Slavic Languages and Literatures Major, B.A.–Slavic and East European Languages and Cultures Concentration",
  "Global American Studies Minor",
  "Global Cinema Minor",
  "Global Studies Major, B.A.",
  "Greek Minor",
  "Health and Society Minor",
  "Health Policy and Management Major, B.S.P.H.",
  "Heritage and Global Engagement Minor",
  "Hindi-Urdu Minor",
  "Hispanic Studies Minor",
  "History Major, B.A.",
  "History Minor",
  "Human and Organizational Leadership and Development, B.A.",
  "Human Development and Family Studies, B.A.Ed.",
  "Information Science Major, B.S.",
  "Information Systems Minor",
  "Interdisciplinary Studies Major, B.A.",
  "Interdisciplinary Studies Major, B.A.–Cultural Studies",
  "Islamic and Middle Eastern Studies Minor",
  "Italian Minor",
  "Japanese Minor",
  "Jewish Studies Minor",
  "Korean Minor",
  "Latin American Studies Major, B.A.",
  "Latin Minor",
  "Latina/o Studies Minor",
  "Linguistics Major, B.A.",
  "Linguistics Minor",
  "Management and Society Major, B.A.",
  "Marine Sciences Minor",
  "Mathematics Major, B.A.",
  "Mathematics Major, B.S.",
  "Mathematics Minor",
  "Media and Journalism Major, B.A.",
  "Media and Journalism Minor",
  "Medical Anthropology Major, B.A.",
  "Medical Anthropology Minor",
  "Medicine, Literature, and Culture Minor",
  "Medieval and Early Modern Studies (MEMS) Minor",
  "Middle Eastern Languages Minor",
  "Military Science and Leadership Minor",
  "Modern Hebrew Minor",
  "Music Major, B.A.",
  "Music Major, Bachelor of Music (B.Mus.)",
  "Music Minor", "Naval Science Minor",
  "Neuroscience Major, B.S.",
  "Neuroscience Minor",
  "Nursing Major, B.S.N.",
  "Nutrition Major, B.S.P.H.",
  "Peace, War, and Defense Major, B.A.",
  "Persian Minor",
  "Philosophy Major, B.A.",
  "Philosophy Minor",
  "Philosophy, Politics, and Economics (PPE) Minor",
  "Physics Major, B.A.",
  "Physics Major, B.S.",
  "Physics Minor",
  "Political Science Major, B.A.",
  "Portuguese Minor",
  "Post Certificate in Dental Hygiene",
  "Psychology Major, B.A.",
  "Psychology Major, B.S.",
  "Public Policy Major, B.A.",
  "Public Policy Minor",
  "Radiologic Science Major, B.S.",
  "Religious Studies Major, B.A.",
  "Religious Studies Major, B.A.–Jewish Studies Concentration",
  "Religious Studies Minor",
  "Romance Languages Major, B.A.–French and Francophone Studies",
  "Romance Languages Major, B.A.–Hispanic Linguistics",
  "Romance Languages Major, B.A.–Hispanic Literatures and Cultures",
  "Romance Languages Major, B.A.–Italian",
  "Romance Languages Major, B.A.–Portuguese",
  "Russian Culture Minor",
  "Sexuality Studies Minor",
  "Slavic and East European Languages and Cultures Minor",
  "Social and Economic Justice Minor",
  "Sociology Major, B.A.",
  "Southern Studies Minor",
  "Spanish Minor for the Professions",
  "Speech and Hearing Sciences Minor",
  "Statistics and Analytics Major, B.S.",
  "Statistics and Analytics Minor",
  "Studio Art Major, B.A.",
  "Studio Art Major, Bachelor of Fine Arts (B.F.A)",
  "Studio Art Major, Bachelor of Fine Arts (B.F.A)–Art History Emphasis",
  "Studio Art Minor",
  "Study of Christianity and Culture Minor",
  "Sustainability Studies Minor",
  "Translation and Interpreting Minor",
  "Urban Studies and Planning Minor",
  "Women’s and Gender Studies Major, B.A.",
  "Women’s and Gender Studies Minor",
  "Writing for the Screen and Stage Minor",
  "Other",
  "Undecided",
];

module.exports = StudyPrograms;
